# Generated by Django 5.1.4 on 2025-01-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_color_options_alter_product_image1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('image', models.ImageField(upload_to='images_advertising/', verbose_name='фото')),
            ],
            options={
                'verbose_name': 'реклама',
                'verbose_name_plural': 'рекламы',
            },
        ),
    ]
