# Generated by Django 5.1.4 on 2025-01-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_product_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(blank=True, null=True, to='market.size', verbose_name='выберите размер'),
        ),
    ]
